// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLz5YMvkJF55OB5cB8J1W6ZEgovSJzw6s',
    appId: '1:854223360801:web:22d091de097659ebd5e460',
    messagingSenderId: '854223360801',
    projectId: 'boxcricket-8bf35',
    authDomain: 'boxcricket-8bf35.firebaseapp.com',
    storageBucket: 'boxcricket-8bf35.firebasestorage.app',
    measurementId: 'G-E7PF0G5PHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIRi00cMV3y4RKV8lgeegusiu-gdrQTI',
    appId: '1:854223360801:android:0c1955a1f33a9a83d5e460',
    messagingSenderId: '854223360801',
    projectId: 'boxcricket-8bf35',
    storageBucket: 'boxcricket-8bf35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCzM98ZOWJCz3D_4Rmo0sXv4kkdrTFnk',
    appId: '1:854223360801:ios:2cfd96cee77d7b1fd5e460',
    messagingSenderId: '854223360801',
    projectId: 'boxcricket-8bf35',
    storageBucket: 'boxcricket-8bf35.firebasestorage.app',
    iosBundleId: 'com.example.boxCricket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCzM98ZOWJCz3D_4Rmo0sXv4kkdrTFnk',
    appId: '1:854223360801:ios:2cfd96cee77d7b1fd5e460',
    messagingSenderId: '854223360801',
    projectId: 'boxcricket-8bf35',
    storageBucket: 'boxcricket-8bf35.firebasestorage.app',
    iosBundleId: 'com.example.boxCricket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLz5YMvkJF55OB5cB8J1W6ZEgovSJzw6s',
    appId: '1:854223360801:web:549288684837a7b5d5e460',
    messagingSenderId: '854223360801',
    projectId: 'boxcricket-8bf35',
    authDomain: 'boxcricket-8bf35.firebaseapp.com',
    storageBucket: 'boxcricket-8bf35.firebasestorage.app',
    measurementId: 'G-GEHVP48RQX',
  );
}
